"""empty message

Revision ID: 939fa1411790
Revises: d66c6374d0a4
Create Date: 2018-11-01 13:29:49.604260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939fa1411790'
down_revision = 'd66c6374d0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rcaddress_ibfk_1', 'rcaddress', type_='foreignkey')
    op.create_foreign_key(None, 'rcaddress', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rcaddress', type_='foreignkey')
    op.create_foreign_key('rcaddress_ibfk_1', 'rcaddress', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
