"""empty message

Revision ID: 93e9e51a4707
Revises: c92778f6856b
Create Date: 2018-10-29 15:57:13.524938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93e9e51a4707'
down_revision = 'c92778f6856b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'intr',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'intr',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
