"""empty message

Revision ID: 9bef815f8d4b
Revises: 
Create Date: 2018-10-17 21:49:13.947444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bef815f8d4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_UserModel__passwd', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('is_delete', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('personal_introduction', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.Enum('man', 'woman', 'secret', 'unknow', name='genderenum'), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
