"""empty message

Revision ID: e908e7cf2eab
Revises: fcfe0addcecb
Create Date: 2018-10-31 13:48:56.037747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e908e7cf2eab'
down_revision = 'fcfe0addcecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_max_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('goods_type', sa.Column('goodsMt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goods_type', 'goods_max_type', ['goodsMt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods_type', type_='foreignkey')
    op.drop_column('goods_type', 'goodsMt_id')
    op.drop_table('goods_max_type')
    # ### end Alembic commands ###
