"""empty message

Revision ID: ef7f667e3fc9
Revises: 93e9e51a4707
Create Date: 2018-10-29 16:52:23.637121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7f667e3fc9'
down_revision = '93e9e51a4707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_goods_middle', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_goods_middle', 'number')
    # ### end Alembic commands ###
