"""empty message

Revision ID: fcfe0addcecb
Revises: 993fdd26e1d3
Create Date: 2018-10-31 12:36:22.277972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfe0addcecb'
down_revision = '993fdd26e1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('goods', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goods', 'goods_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.drop_column('goods', 'type_id')
    op.drop_table('goods_type')
    # ### end Alembic commands ###
